# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(338, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputLabel.setLineWidth(3)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.operatorCheck("%"))
        self.percentButton.setGeometry(QtCore.QRect(10, 90, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.operatorCheck("/"))
        self.divideButton.setGeometry(QtCore.QRect(250, 90, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.remove())
        self.arrowButton.setGeometry(QtCore.QRect(170, 90, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("C"))
        self.cButton.setGeometry(QtCore.QRect(90, 90, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.operatorCheck("*"))
        self.multiplyButton.setGeometry(QtCore.QRect(250, 170, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(170, 170, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 170, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(90, 170, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.operatorCheck("+"))
        self.addButton.setGeometry(QtCore.QRect(250, 330, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(170, 330, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 330, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(90, 330, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.operatorCheck("-"))
        self.minusButton.setGeometry(QtCore.QRect(250, 250, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(170, 250, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 250, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(90, 250, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.solve())
        self.equalButton.setGeometry(QtCore.QRect(250, 410, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dot())
        self.decimalButton.setGeometry(QtCore.QRect(170, 410, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        self.plusminusButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.plus_minus())
        self.plusminusButton.setGeometry(QtCore.QRect(10, 410, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setObjectName("plusminusButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(90, 410, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 338, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # changing sign of the number
    def plus_minus(self):
        screen = self.outputLabel.text()
        for i in range(len(screen) - 1, -1, -1):
            if i == 0:
                if screen[i] == '-':
                    screen = screen[1:]
                else:
                    screen = "-" + screen
            else:
                if screen[i] == '-':
                    screen = screen[:i] + '+' + screen[i + 1:]
                    break
                elif screen[i] == '+':
                    screen = screen[:i] + '-' + screen[i + 1:]
                    break
                else:
                    continue
        self.outputLabel.setText(screen)

    # remove last character
    def remove(self):
        screen = self.outputLabel.text()
        screen = screen[:-1]
        self.outputLabel.setText(screen)

    def operatorCheck(self, op):
        screen = self.outputLabel.text()
        if screen[-1] == '+' or screen[-1] == '-' or screen[-1] == '*' or screen[-1] == '/' or screen[-1] == '%' or \
                screen[-1] == '.':
            self.outputLabel.setText(screen)
        else:
            self.outputLabel.setText(f'{screen}{op}')

    # solve
    def solve(self):
        screen = self.outputLabel.text()
        try:
            answer = eval(screen)  # evaluate the value of the mathematical function in form of string
            answer = "{0:.2f}".format(answer)
            # display result
            self.outputLabel.setText(str(answer))

        except:
            self.outputLabel.setText('ERROR')

    # decimal
    def dot(self):
        screen = self.outputLabel.text()
        if screen[-1] == '.' or screen[-1] == '+' or screen[-1] == '-' or screen[-1] == '*' or screen[-1] == '/' or \
                screen[-1] == '%':
            pass
        else:
            flag = 0
            for i in range(len(screen) - 1, -1, -1):
                if screen[i] == '+' or screen[i] == '-' or screen[i] == '*' or screen[i] == '/' or screen[i] == '%':
                    break
                elif screen[i] == '.':
                    flag += 1
                    break
                else:
                    continue
            if flag == 0:
                self.outputLabel.setText(f'{screen}.')
            else:
                self.outputLabel.setText(screen)

    def press_it(self, pressed):
        if pressed == "C":
            self.outputLabel.setText("0")
        else:
            if self.outputLabel.text() == "0" or self.outputLabel.text() == 'ERROR':
                self.outputLabel.setText("")

            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.arrowButton.setText(_translate("MainWindow", "<<"))
        self.cButton.setText(_translate("MainWindow", "DEL"))
        self.multiplyButton.setText(_translate("MainWindow", "X"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.plusminusButton.setText(_translate("MainWindow", "+/-"))
        self.zeroButton.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
