# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final_calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 563)
        MainWindow.setStyleSheet("QWidget\n"
                                 "{\n"
                                 "    \n"
                                 "    background-color: rgb(0, 0, 0);\n"
                                 "    color: #ffffff;\n"
                                 "    border-color: #181c21;\n"
                                 "\n"
                                 "}\n"
                                 "QPushButton\n"
                                 "{\n"
                                 "    background-color: #e1f4ff;\n"
                                 "    color: #000000;\n"
                                 "    border-style: solid;\n"
                                 "    border-color: #181c21;\n"
                                 "    border-width: 2px;\n"
                                 "    border-radius:35px;\n"
                                 "    font-weight: bold;\n"
                                 "    font-size: 24px;\n"
                                 "    font-family: Arial;\n"
                                 "}\n"
                                 "QPushButton::hover\n"
                                 "{\n"
                                 "    background-color:  yellow;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QPushButton::pressed\n"
                                 "{\n"
                                 "    background-color: #ffffff;\n"
                                 "}\n"
                                 "QPushButton#equalButton\n"
                                 "{\n"
                                 "    background-color:#58e8b8;\n"
                                 "    color: #000000;\n"
                                 "    border-style: solid;\n"
                                 "    border-color: #181c21;\n"
                                 "    border-width: 2px;\n"
                                 "    border-radius:35px;\n"
                                 "    font-weight: bold;\n"
                                 "    font-size: 40px;\n"
                                 "    font-family: Arial;\n"
                                 "}\n"
                                 "QPushButton#equalButton::hover\n"
                                 "{\n"
                                 "     /*#f6fbff;*/\n"
                                 "    background-color: red;\n"
                                 "}\n"
                                 "QPushButton#equalButton::pressed\n"
                                 "{\n"
                                 "    \n"
                                 "    background-color:white;\n"
                                 "}\n"
                                 "QLineEdit\n"
                                 "{\n"
                                 "    background-color: #12160c;\n"
                                 "    color: rgb(255, 255, 255);\n"
                                 "    border:transparent;\n"
                                 "    border-radius:20px;\n"
                                 "    border-bottom: 2px solid    #ffffff;\n"
                                 "    border-left: 2px solid    #ffffff;\n"
                                 "    padding: 3px;\n"
                                 "}\n"
                                 "QLabel\n"
                                 "{\n"
                                 "    background-color: #12160c;\n"
                                 "    color: rgb(255, 255, 255);\n"
                                 "    border:transparent;\n"
                                 "    border-radius:35px;\n"
                                 "    border-bottom: 2px solid    #ffffff;\n"
                                 "    border-left: 2px solid    #ffffff;\n"
                                 "    padding: 3px;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.modButton = QtWidgets.QPushButton(self.centralwidget)
        self.modButton.setGeometry(QtCore.QRect(10, 120, 71, 71))
        self.modButton.setObjectName("modButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget)
        self.divideButton.setGeometry(QtCore.QRect(310, 120, 71, 71))
        self.divideButton.setObjectName("divideButton")
        self.eraseButton = QtWidgets.QPushButton(self.centralwidget)
        self.eraseButton.setGeometry(QtCore.QRect(210, 120, 71, 71))
        self.eraseButton.setObjectName("eraseButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(110, 120, 71, 71))
        self.clearButton.setObjectName("clearButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget)
        self.eightButton.setGeometry(QtCore.QRect(110, 200, 71, 71))
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget)
        self.nineButton.setGeometry(QtCore.QRect(210, 200, 71, 71))
        self.nineButton.setObjectName("nineButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget)
        self.multiplyButton.setGeometry(QtCore.QRect(310, 200, 71, 71))
        self.multiplyButton.setObjectName("multiplyButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget)
        self.sevenButton.setGeometry(QtCore.QRect(10, 200, 71, 71))
        self.sevenButton.setObjectName("sevenButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.fiveButton.setGeometry(QtCore.QRect(110, 280, 71, 71))
        self.fiveButton.setObjectName("fiveButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget)
        self.sixButton.setGeometry(QtCore.QRect(210, 280, 71, 71))
        self.sixButton.setObjectName("sixButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusButton.setGeometry(QtCore.QRect(310, 280, 71, 71))
        self.plusButton.setObjectName("plusButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget)
        self.fourButton.setGeometry(QtCore.QRect(10, 280, 71, 71))
        self.fourButton.setObjectName("fourButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget)
        self.twoButton.setGeometry(QtCore.QRect(110, 360, 71, 71))
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget)
        self.threeButton.setGeometry(QtCore.QRect(210, 360, 71, 71))
        self.threeButton.setObjectName("threeButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget)
        self.minusButton.setGeometry(QtCore.QRect(310, 360, 71, 71))
        self.minusButton.setObjectName("minusButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget)
        self.oneButton.setGeometry(QtCore.QRect(10, 360, 71, 71))
        self.oneButton.setObjectName("oneButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget)
        self.zeroButton.setGeometry(QtCore.QRect(110, 440, 71, 71))
        self.zeroButton.setObjectName("zeroButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget)
        self.decimalButton.setGeometry(QtCore.QRect(210, 440, 71, 71))
        self.decimalButton.setObjectName("decimalButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget)
        self.equalButton.setGeometry(QtCore.QRect(310, 440, 71, 71))
        self.equalButton.setStyleSheet("")
        self.equalButton.setObjectName("equalButton")
        self.plusminusButton = QtWidgets.QPushButton(self.centralwidget)
        self.plusminusButton.setGeometry(QtCore.QRect(10, 440, 71, 71))
        self.plusminusButton.setObjectName("plusminusButton")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(10, 10, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.outputlabel.setFont(font)
        self.outputlabel.setStyleSheet("")
        self.outputlabel.setPixmap(QtGui.QPixmap(":/newPrefix/blacksmoke.jpg"))
        self.outputlabel.setScaledContents(False)
        self.outputlabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.outputlabel.setWordWrap(False)
        self.outputlabel.setObjectName("outputlabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modButton.setText(_translate("MainWindow", "MOD"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.eraseButton.setText(_translate("MainWindow", "<<"))
        self.clearButton.setText(_translate("MainWindow", "CLR"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.multiplyButton.setText(_translate("MainWindow", "*"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.plusminusButton.setText(_translate("MainWindow", "+/-"))
        self.outputlabel.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
